name: CI
on: push
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Pull Docker base images
        run: |
          docker pull golang:1.18.1-bullseye@sha256:3b1a72af045ad0fff9fe8e00736baae76d70ff51325ac5bb814fe4754044b972
          docker pull ruby:3.1.2-bullseye@sha256:e75f1da5372940f6997c94c9c48db8e4292fb625ca49035fa53e7e5b9124d6fb
      - name: Use Docker layer caching
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Build for Staging
        run: docker build . -t ghcr.io/lutriseng/parts-registry:staging --build-arg RAILS_ENV=staging
      - name: Build for Production
        run: docker build . -t ghcr.io/lutriseng/parts-registry:production --build-arg RAILS_ENV=production
      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.9.0
      - name: Setup test database
        env:
          RAILS_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        run: |
          cp config/database.yml.github-actions config/database.yml
          bin/rails db:create
          bin/rails db:schema:load
      - name: Run tests
        env:
          RAILS_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        run: bin/rails test
