name: Deploy
concurrency: production
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up Fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Build and push staging
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/lutriseng/parts-registry:staging
          cache-from: type=registry,ref=ghcr.io/lutriseng/parts-registry:cache
          cache-to: type=registry,ref=ghcr.io/lutriseng/parts-registry:cache,mode=max
          build-args: RAILS_ENV=staging
      - name: Build and push production
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/lutriseng/parts-registry:production
          cache-from: type=registry,ref=ghcr.io/lutriseng/parts-registry:cache
          cache-to: type=registry,ref=ghcr.io/lutriseng/parts-registry:cache,mode=max
          build-args: RAILS_ENV=production
      - name: Deploy staging
        run: ./deploy-staging.sh --local-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Deploy production
        run: ./deploy-production.sh --local-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
